# Generated by Django 2.2.5 on 2019-11-24 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('util', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='conten',
            new_name='content',
        ),
    ]
